### ISSUE TITLE
Tank level showing as problem while not full. (binary sensor logic problem)

### ISSUE THREAD

**Issue by verhoop** [georgezhao2010/midea_ac_lan#300]
### HA core version

2023.9.1

### Intergration version

0.3.20

### Device type and model

Dehumidifier 00000Q10

### Used App

MSmartHome / local polling

### The description of problem

My dehumidifier has 4 different levels indicating how full the tank is. 
When the level reaches 1/4 full. ("25") the binary sensor indicates that there is a problem. (even when the "water_level_set" is set to "100". 
Binary sensor should be triggered when "tank" is equal or higher than "water_level_set"  

### The logs

2023-09-10 15:32:08.128 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 25, 'water_level_set': '100', 'current_humidity': 57, 'current_temperature': 23.0}
2023-09-10 15:32:09.141 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff000000000000000000000000000000006372', 'message type': '03', 'body type': '41'}
2023-09-10 15:32:09.258 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000303', 'body': 'c80104507f7f002800401900000000643960000000000063f0', 'message type': '03', 'body type': 'c8'}
2023-09-10 15:32:09.259 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 25, 'water_level_set': '100', 'current_humidity': 57, 'current_temperature': 23.0}
2023-09-10 15:32:10.266 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff0000000000000000000000000000000001ab', 'message type': '03', 'body type': '41'}
2023-09-10 15:32:10.393 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000303', 'body': 'c80104507f7f00280040190000000064396000000000000129', 'message type': '03', 'body type': 'c8'}
2023-09-10 15:32:10.394 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 25, 'water_level_set': '100', 'current_humidity': 57, 'current_temperature': 23.0}
2023-09-10 15:32:11.398 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff000000000000000000000000000000000249', 'message type': '03', 'body type': '41'}
2023-09-10 15:32:11.500 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000303', 'body': 'c80104507f7f002800401900000000643960000000000002cb', 'message type': '03', 'body type': 'c8'}
2023-09-10 15:32:11.500 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 25, 'water_level_set': '100', 'current_humidity': 57, 'current_temperature': 23.0}
2023-09-10 15:32:12.504 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff000000000000000000000000000000000317', 'message type': '03', 'body type': '41'}
2023-09-10 15:32:12.621 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000303', 'body': 'c80104507f7f00280040190000000064396000000000000395', 'message type': '03', 'body type': 'c8'}
2023-09-10 15:32:12.621 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 25, 'water_level_set': '100', 'current_humidity': 57, 'current_temperature': 23.0}
2023-09-10 15:32:13.624 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff000000000000000000000000000000000494', 'message type': '03', 'body type': '41'}
2023-09-10 15:32:13.741 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000303', 'body': 'c80104507f7f00280040190000000064396000000000000416', 'message type': '03', 'body type': 'c8'}
2023-09-10 15:32:13.741 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 25, 'water_level_set': '100', 'current_humidity': 57, 'current_temperature': 23.0}
2023-09-10 15:32:14.742 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff0000000000000000000000000000000005ca', 'message type': '03', 'body type': '41'}

**Comment by georgezhao2010** [comment]
> ### The description of problem
> My dehumidifier has 4 different levels indicating how full the tank is. When the level reaches 1/4 full. ("25") the binary sensor indicates that there is a problem. (even when the "water_level_set" is set to "100". Binary sensor should be triggered when "tank" is equal or higher than "water_level_set"

Got it. I'll take a look.

**Comment by verhoop** [comment]
cool!!! appreciate it! 
tank level just increased to 50

2023-09-10 18:57:51.647 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff000000000000000000000000000000005170', 'message type': '03', 'body type': '41'}
2023-09-10 18:57:51.754 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000303', 'body': 'c80104507f7f002800403200000000643a60000000000051c7', 'message type': '03', 'body type': 'c8'}
2023-09-10 18:57:51.755 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 50, 'water_level_set': '100', 'current_humidity': 58, 'current_temperature': 23.0}
2023-09-10 18:57:52.755 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000305', 'body': 'a00104507f7f002800403200000000643a600000000000512e', 'message type': '05', 'body type': 'a0'}
2023-09-10 18:57:52.755 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Status update: {'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 40, 'anion': True, 'tank': 50, 'water_level_set': '100', 'current_humidity': 58, 'current_temperature': 23.0}
2023-09-10 18:58:01.772 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.core.device] [153931628044858] Sending: {'header': 'aa20a100000000000303', 'body': '418100ff000000000000000000000000000000005292', 'message type': '03', 'body type': '41'}
2023-09-10 18:58:01.879 DEBUG (Dehumidifier) [custom_components.midea_ac_lan.midea.devices.a1.device] [153931628044858] Received: {'header': 'aa23a100000000000303', 'body': 'c80104507f7f002800403200000000643a6000000000005225', 'message type': '03', 'body type': 'c8'}

**Comment by verhoop** [comment]
Prettiest would be ; adding a regular sensor with water level. (Amount of %) and the tank warning with the earlier stated logic.

**Comment by georgezhao2010** [comment]
> Prettiest would be ; adding a regular sensor with water level. (Amount of %) and the tank warning with the earlier stated logic.

Is it correct to understand that when the water level exceeds a predetermined level, the binary sensor should indicate a problem? For instance, if the water level is set at 50, then the binary sensor should display ‘problem’ when the tank’s water level reaches or surpasses 50.

**Comment by verhoop** [comment]
Yes correct!
If ‘tank’ => ‘water_level_set’

**Comment by georgezhao2010** [comment]
> Yes correct! If ‘tank’ => ‘water_level_set’ then it should indicate problem. I’m not sure how the actual unit measures the water level tho. Assuming it is applying some kind of logic and clears it when the bucket has been removed for x period of time.

You can pull the newest code in dev branch. It chages the Tank as a sensor and added a Tank Status binary sensor.

Try and see if them works.

**Comment by verhoop** [comment]
Cool! 
Just copied the dev files into the custom dir, 
restarted HA, removed the device and added it again. 
didnt see a change in the sensors tho.
Will the added entities popup when the level reaches 25 %? 
Or is my way of pulling the dev files wrong?

**Comment by georgezhao2010** [comment]
> Cool! Just copied the dev files into the custom dir, restarted HA, removed the device and added it again. didnt see a change in the sensors tho. Will the added entities popup when the level reaches 25 %? Or is my way of pulling the dev files wrong?

dev branch is here https://github.com/georgezhao2010/midea_ac_lan/tree/dev

**Comment by verhoop** [comment]
new sensors are showing, but not showing status.
Also temp and humidity level are not coming through. 

![IMG_6656](https://github.com/georgezhao2010/midea_ac_lan/assets/29624377/cebfaeca-5456-48e3-986d-c0dab981e1b4)

**Comment by georgezhao2010** [comment]
> new sensors are showing, but not showing status. Also temp and humidity level are not coming through.

OK, I fixed it, pull and try again.

**Comment by verhoop** [comment]
> > new sensors are showing, but not showing status. Also temp and humidity level are not coming through.
> 
> OK, I fixed it, pull and try again.

Still the same. 
Pulled the new files, delete thedevice. 
Added the device and restarted HA.

This error originated from a custom integration.

Logger: custom_components.dev_midea_ac_lan.midea.core.device
Source: custom_components/dev_midea_ac_lan/midea/core/device.py:330
Integration: dev_midea_ac_lan
First occurred: 1:18:46 PM (1 occurrences)
Last logged: 1:18:46 PM

[153931628044858] Error in process message, msg = aa23a100000000000303c80104507f7f002d0040000000000064295e00000000000122a0

**Comment by georgezhao2010** [comment]
> > > new sensors are showing, but not showing status. Also temp and humidity level are not coming through.
> > 
> > 
> > OK, I fixed it, pull and try again.
> 
> Still the same. Pulled the new files, delete thedevice. Added the device and restarted HA.
> 
> This error originated from a custom integration.
> 

Are you sure the code you pulled is from the dev branch? In testing, the code in the dev branch can parse the message in your log.

```python
{'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Clothes-Dry', 'fan_speed': 'High', 'swing': False, 'target_humidity': 45, 'anion': True, 'tank': 0, 'water_level_set': '100', 'current_humidity': 41, 'current_temperature': 22.0}
```

**Comment by verhoop** [comment]
Deleted the integration. Installed the integration via HACS, rebooted the HA server, downloaded the files from the dev branch and copied them in the folder (overwrite the existing files) then add the dehumidifier again, 
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/29624377/4e03bbcf-26f1-471d-8c4f-b70ec584e7de)

**Comment by verhoop** [comment]
I had an old dev_ folder in the customer repository directory which was causing confusions. 
After removing that directory and pulling the dev branch again it started working properly! :)
Great work!!! 

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/29624377/146fb54a-b434-432c-9ca9-e9f02b129994)

**Comment by georgezhao2010** [comment]
> I had an old dev_ folder in the customer repository directory which was causing confusions.
> After removing that directory and pulling the dev branch again it started working properly! :)
> Great work!!!

OK, I'll close this issue.
