### ISSUE TITLE
Stuck on Beta 0.2.0-B2

### ISSUE THREAD

**Issue by fuchS31337** [georgezhao2010/midea_ac_lan#32]
Hi there :-)

Somehow I'm stuck on 0.2.0-B2, HACS is promoting an update to 0.2.3, but it does nothing when I click it. When I try to open the Integration Page there is a "Unknown Error".

Tried a few things, including deleting the deps folder and poking around in .storage. Whilst doing that I recognized that

.storage/hacs/repository/396083412.hacs

is missing.

Can someone send me that file, maybe that solves my problem?

Best regards

Michael

**Comment by fuchS31337** [comment]
Following Logs come alog with that:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/integration.py:157
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 27. Juli 2022 um 15:21:43 (8 occurrences)
Last logged: 14:23:06

[139737589302128] Error handling message: Unknown error (unknown_error)
[139737475063600] Error handling message: Unknown error (unknown_error)
[139736987031664] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/integration.py", line 110, in update_repository
    if manifest := await self.async_get_integration_manifest():
  File "/config/custom_components/hacs/repositories/integration.py", line 157, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No manifest.json file found 'custom_components/None/manifest.json'

**Comment by georgezhao2010** [comment]
> Hi there :-)
> 
> Somehow I'm stuck on 0.2.0-B2, HACS is promoting an update to 0.2.3, but it does nothing when I click it. When I try to open the Integration Page there is a "Unknown Error".
> 
> Tried a few things, including deleting the deps folder and poking around in .storage. Whilst doing that I recognized that
> 
> .storage/hacs/repository/396083412.hacs
> 
> is missing.
> 
> Can someone send me that file, maybe that solves my problem?
> 
> Best regards
> 
> Michael

The file `.storage/hacs/repository/396083412.hacs`  does not exist in my HomeAssistant.
Sounds like some files is bad or missing. 
Try download this repository and put `midea_ac_lan` into `custom_components` folder manually?

**Comment by fuchS31337** [comment]
Yes, already tried that, no change

> The file .storage/hacs/repository/396083412.hacs does not exist in my HomeAssistant.
Sounds like some files is bad or missing.
Try download this repository and put midea_ac_lan into custom_components folder manually?

**Comment by georgezhao2010** [comment]
> Yes, already tried that, no change
> 
> > The file .storage/hacs/repository/396083412.hacs does not exist in my HomeAssistant.
> > Sounds like some files is bad or missing.
> > Try download this repository and put midea_ac_lan into custom_components folder manually?

How about now? It was solved?

**Comment by fuchS31337** [comment]
No, not solved yet.
But I again copied the repository manually into the custom folder and that changed the version, there are differences in the menu for example. Manually upgrading works, so far so good.

The empty hacs update notification stays.
Could you please send me this file:

 .storage/hacs/repository/396083412.hacs 

Maybe it helps :/
